### ISSUE TITLE
Use with statement to ensure file handles are closed

### ISSUE THREAD

**Issue by svisser** [alixander/PyScribe#4]
Various files are being opened and manually closed by `.close()` but this means, if an exception were to occur, the file isn't closed. It's better to use the [with statement][1] here as this ensures the files are indeed closed, even when exceptions occur.

[1]: http://effbot.org/zone/python-with-statement.htm

**Comment by alixander** [comment]
Oh man I was looking for a function like that (specifically, a `defer close` statement like in Go/other languages), and forgot about `with`. Thanks, I'll change it to use `with` soon.

**Comment by kragniz** [comment]
I saw the title of this issue and knew who was the culprit.

**Comment by svisser** [comment]
Well, I have indeed filed this issue in multiple projects as it's a common thing. Installation using `setup.py` enables many things but it's also weird that it requires arbitrary code execution to install the package. So it makes sense to treat it as any other code (closing file handles etc).

**Comment by alixander** [comment]
https://github.com/alixander/PyScribe/pull/7
